apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: my-app
    chart: mysql
    release: my-app
spec:
  selector:
    matchLabels:
      app: my-app
      release: my-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        requires_envoy: "false"
      labels:
        app: my-app
        release: my-app
        team: pde
    spec:
      serviceAccountName: oshiya-dev
      automountServiceAccountToken: true
      securityContext:
        runAsUser: 50000
      volumes:
      - name: writeable-path
        emptyDir: {}
      - name: rds-cert
        configMap:
          name: rds-cert
      securityContext:
        runAsUser: 50000
      restartPolicy: Always
      tolerations:
        - key: "workload"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "3"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 500Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test2020
          volumeMounts:
            - name: writeable-path
              mountPath: /var/lib/mysql
              readOnly: false
            - name: rds-cert
              mountPath: /etc/ssl/certs/rds-combined-ca-bundle.pem
              subPath: rds-combined-ca-bundle.pem
              readOnly: false
          command: ["sh"]
          args: ["-c", "sleep 36000"]
          # command: ["sh"]
          # args: ["-c", "sleep 36000"]
          # env:
          #   - name: HOME
          #     value: /root
          # volumeMounts:
          #   - name: s3-root
          #     mountPath: /root
          #     readOnly: false
